steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "laravel-docker"
      - "--image=gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
logsBucket: "gs://laravel-buckets-1/logs"
