steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
      - "--build-arg"
      - "DB_CONNECTION=mysql"
      - "--build-arg"
      - "DB_HOST=$(cat /workspace/get-secrets.stdout | jq -r .payload.data.DB_HOST)" # Extract the secret value
      - "--build-arg"
      - "DB_PORT=3306"
      - "--build-arg"
      - "DB_DATABASE=$(cat /workspace/get-secrets.stdout | jq -r .payload.data.DB_NAME)" # Extract the secret value
      - "--build-arg"
      - "DB_USERNAME=$(cat /workspace/get-secrets.stdout | jq -r .payload.data.DB_USERNAME)" # Extract the secret value
      - "--build-arg"
      - "DB_PASSWORD=$(cat /workspace/get-secrets.stdout | jq -r .payload.data.DB_PASSWORD)" # Extract the secret value
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "laravel-docker"
      - "--image=gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/laravel-docker:$COMMIT_SHA"
logsBucket: "gs://laravel-buckets-final/logs"
